version: '3.8'

services:
  frontend:
    build: .
    container_name: todo-ui
    ports:
      - '3000:3000'
    networks:
      - todo-list-network
    volumes:
      - .:/app:rw,cached

networks:
  todo-list-network:
    name: todo-list-network
    external: true
