version: '3.8'

services:
  frontend:
    build: .
    container_name: todo-ui
    ports:
      - '3000:3000'
    networks:
      - todo-list-network
    develop:
      watch:
        - action : sync
          path: .
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json

networks:
  todo-list-network:
    name: todo-list-network
    external: true
